### ISSUE TITLE
install jeemy version on ubuntu 22.4

### ISSUE THREAD

**Issue by swa2050** [rajannpatel/ubuntupbx#3]
![error2](https://user-images.githubusercontent.com/122435442/211753601-51e10dde-31ec-4c72-bf90-72b0a2071007.JPG)

i tried to install have issue

**Comment by rajannpatel** [comment]
You need to reconnect to the instance via SSH, and as root, run the following commands:
```console
fwconsole ma downloadinstall customappsreg featurecodeadmin framework pm2 recordings soundlang calendar callrecording conferences core ivr infoservices queues ringgroups timeconditions asteriskinfo cel voicemail sipsettings logfiles dashboard music filestore backup
fwconsole chown
fwconsole reload
sed -i 's/\(^upload_max_filesize = \).*/\120M/' /etc/php/7.4/apache2/php.ini
sed -i 's/\(^memory_limit = \).*/\1256M/' /etc/php/7.4/apache2/php.ini
sed -i 's/^\(User\|Group\).*/\1 asterisk/' /etc/apache2/apache2.conf
sed -i 's/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf
a2enmod rewrite
systemctl restart apache2
rm /var/www/html/index.html
sed -i 's#Socket=/var/lib/mysql/mysql.sock#Socket=/var/run/mysqld/mysqld.sock#g' /etc/odbc.ini
fwconsole restart
systemctl daemon-reload
systemctl enable freepbx
reboot
```
This should be sufficient to resolve your issue, which I was able to replicate. If this does not resolve your issue, we can try reinstalling FreePBX. This used to work and appears to have broken recently, perhaps due to code changes in the FreePBX project. Please report back if your issue is resolved or not, and I will look for a better fix.

**Comment by rajannpatel** [comment]
Installing the PM2 and Framework modules first resolves this issue. Thank you for reporting it! Please reopen the ticket if this fix does not solve your problem.

**Comment by rajannpatel** [comment]
The latest https://github.com/rajannpatel/ubuntupbx/blob/main/jammy/install.sh does not have this issue
